[general]
live_config_reload = true       # Recarga al guardar cambios

[env]
TERM = "xterm-256color"

[terminal.shell]
program = "wsl.exe"            	# Ejecuta WSL por defecto
args = ["~"]			# Inicia en el Home de WSL


[terminal]                   
osc52 = "CopyPaste"

[window]
decorations = "Buttonless"     	# Sin bordes de ventana
dynamic_title = false          	# Título dinámico
startup_mode = "Maximized"    	# Pantalla completa
opacity = 0.80                	# Más transparente
blur = true                    	# Efecto de desenfoque (Win 10+)

[window.padding]
x = 25
y = 10

[keyboard]
bindings = [
    { key = "F11", action = "ToggleFullscreen" }, 		# Pantalla completa
    { key = "V", mods = "Control|Shift", action = "Paste" }, 	# Pegar
    { key = "C", mods = "Control|Shift", action = "Copy" }, 	# Copiar
  
]

[scrolling]
history = 10000                # Historial amplio
multiplier = 3                 # Velocidad del scroll

[font]
size = 12.0                  # Tamaño de la fuente
glyph_offset = { y = 1 }     # Desplazamiento vertical de la fuente

[font.normal]
family = "Maple Mono NF"
style = "Regular"

[cursor]
style.shape = "Block"                # "Beam" para modo inserción
style.blinking = "On"                # Cursor parpadeante

# Catppuccin theme
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"
